name: CI - Docker Compose

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy .env
        run: cp .env.example .env

      - name: Build & start Docker Compose
        run: docker-compose up -d --build

      - name: Wait for PostgreSQL
        run: |
          echo "Waiting for Postgres..."
          until docker exec pgdb pg_isready -U $DB_USERNAME; do sleep 2; done

      - name: Generate Laravel key
        run: docker-compose exec app php artisan key:generate

      - name: Run migrations
        run: docker-compose exec app php artisan migrate --force

      - name: Run tests
        run: docker-compose exec app vendor/bin/phpunit --configuration phpunit.xml

      - name: Shutdown Docker Compose
        run: docker-compose down
